[workspace]
members = ["macros","rust-test"]

[package]
name = "std-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"


[dependencies]
wasm-bindgen = "0.2.92"
macros = { path = "./macros" }
tokio = { version = "1.36.0", features = ["sync", "macros", "io-util", "rt", "time"] }
js-sys = "0.3.69"
wasm-bindgen-futures = { version = "0.4.42", features = ["futures-core", "futures-core-03-stream"] }
